set JAHIA_VERSION="LATEST"
set JAHIA_IMAGE="jahia/jahia-discovery-dev:8-SNAPSHOT"
set TESTS_IMAGE="jahia/graphql-dxm-provider:latest"
set MODULE_ID="graphql-dxm-provider"
set MANIFEST="provisioning-manifest-snapshot.yml"
set JAHIA_URL="http://localhost:8080"
set SUPER_USER_PASSWORD="root1234"
set LDAP_TAG="1.0.0"
