version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  jahia-modules-orb: jahia/jahia-modules-orb@0.2.0

references:
  workdir: &workdir
    working_directory: ~/source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .


commands:
  generate_cachekey_seed:
    description: Generate Cache Key Seeds
    steps:
      - run:
          name: Generate Cache Key Seeds
          command: |
            find . -name 'pom.xml' | sort | xargs cat > ~/source/maven_cache_seed
            if [[ ! -z "$CIRCLE_PULL_REQUEST" ]]; then
              echo "true" > ~/source/is_pr
            else
              echo "false" > ~/source/is_pr
            fi

jobs:
  checkout:
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - *persist-workspace


  build:
    parameters:
      is_pull_request:
        type: boolean
        default: false
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: large
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - when:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: mvn clean install
                command: mvn -s .circleci/.circleci.settings.xml clean install
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: mvn clean deploy
                command: mvn -s .circleci/.circleci.settings.xml clean deploy
      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Copy artifacts
          command: |
            mkdir /tmp/artifacts/
            cp /home/circleci/source/graphql-dxm-provider/target/*.jar /tmp/artifacts/
            cp /home/circleci/source/graphql-extension-example/target/*.jar /tmp/artifacts/
            cp /home/circleci/source/graphql-test/target/*.jar /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
      - *persist-workspace

  sonar:
    parameters:
      is_pull_request:
        type: boolean
        default: false
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: large
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - when:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Analyze pull request with sonar
                command: |
                  mvn -s .circleci/.circleci.settings.xml sonar:sonar -Dsonar.pullrequest.branch=$CIRCLE_BRANCH \
                  -Dsonar.pullrequest.key=<< pipeline.parameters.pull_request_number >> \
                  -Dsonar.pullrequest.base=<< pipeline.parameters.target_branch >> \
                  -Dsonar.pullrequest.github.repository=<< pipeline.parameters.github_repository >>
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Sonar analysis
                command: |
                  if [[ "${CIRCLE_BRANCH}" == "master" ]];
                  then
                    mvn -s .circleci/.circleci.settings.xml sonar:sonar
                  else
                    mvn -s .circleci/.circleci.settings.xml sonar:sonar -Dsonar.branch.name=$CIRCLE_BRANCH
                  fi
      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "pom.xml" }}

# Pipeline parameter must be declared
parameters:
  run_pull_request:
    type: boolean
    default: false
  target_branch:
    type: string
    default: ""
  pull_request_number:
    type: string
    default: ""
  github_repository:
    type: string
    default: ""
  GITHUB_SLUG:
    type: string
    default: "jahia/graphql-core"
  MODULE_ID:
    type: string
    default: "graphql-dxm-provider"
  SSH_KEY_FINGERPRINT:
    type: string
    default: "de:83:a2:6f:fe:89:6c:6c:34:58:55:f1:82:76:51:11"
  PRIMARY_RELEASE_BRANCH:
    type: string
    default: "1_x"
  RELEASE_ID:
    type: string
    default: ""
  RELEASE_VERSION:
    type: string
    default: ""
  IS_RELEASE:
    type: boolean
    default: false

workflows:
  version: 2
  # This one is run only when triggered with the API, using a GitHub action
  on-release:
    when: << pipeline.parameters.IS_RELEASE >>
    jobs:
      - jahia-modules-orb/initialize
      - jahia-modules-orb/generate-changelog:
          context: QA_ENVIRONMENT
          requires:
            - jahia-modules-orb/initialize
          ssh_key_fingerprints: << pipeline.parameters.SSH_KEY_FINGERPRINT >>
      - jahia-modules-orb/release:
          context: QA_ENVIRONMENT
          requires:
            - jahia-modules-orb/generate-changelog
          module_id: << pipeline.parameters.MODULE_ID >>
          github_slug: << pipeline.parameters.GITHUB_SLUG >>
          release_id: << pipeline.parameters.RELEASE_ID >>
          release_version: << pipeline.parameters.RELEASE_VERSION >>
          primary_release_branch: << pipeline.parameters.PRIMARY_RELEASE_BRANCH >>
          ssh_key_fingerprints: << pipeline.parameters.SSH_KEY_FINGERPRINT >>
      - jahia-modules-orb/update-signature:
          context: QA_ENVIRONMENT
          requires:
            - jahia-modules-orb/release
          ssh_key_fingerprints: << pipeline.parameters.SSH_KEY_FINGERPRINT >>
      - wait-for-approval:
          type: approval
          context: QA_ENVIRONMENT
          requires:
            - jahia-modules-orb/release
      - jahia-modules-orb/release-publication:
          context: QA_ENVIRONMENT
          requires:
            - wait-for-approval
          module_id: << pipeline.parameters.MODULE_ID >>
          release_version: << pipeline.parameters.RELEASE_VERSION >>
  pull_request:
    when: << pipeline.parameters.run_pull_request >>
    jobs:
      - checkout:
          name: PR Checkout
      - build:
          name: PR Build
          is_pull_request: true
          context: QA_ENVIRONMENT
          requires:
            - PR Checkout
      - sonar:
          name: PR Sonar analysis
          is_pull_request: true
          context: QA_ENVIRONMENT
          requires:
            - PR Build
  on-code-change:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
                - /feature-.*/
                - /[0-9]_[0-9]_x/
                - /[0-9]_x/
      - build:
          is_pull_request: false
          context: QA_ENVIRONMENT
          requires:
            - checkout
      - sonar:
          name: Sonar analysis
          is_pull_request: false
          context: QA_ENVIRONMENT
          requires:
            - build
