name: Nightly Test run (Jahia SN)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: graphql-dxm-provider
      testrail_project: GraphQL Core module
      pagerduty_incident_service: graphql-dxm-provider-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: gql
      module_branch: ${{ github.ref }}

