# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  on-code-change:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-on-code-change.yml@v2
    secrets: inherit
    with:
      integration_tests_jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: graphql-dxm-provider
      integration_tests_testrail_project: GraphQL Core module
      integration_tests_pagerduty_skip_notification: true
      integration_tests_provisioning_manifest: provisioning-manifest-build.yml
      integration_tests_should_use_build_artifacts: true
      integration_tests_artifact_prefix: gql
      static_analysis_node_version: latest
      static_analysis_auditci_level: critical
      module_branch: ${{ github.head_ref }}
      build_instance_type: self-hosted
      integration_tests_standalone_execute: true
