# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  on-code-change:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-on-code-change.yml@reusable-on-code-change
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: graphql-dxm-provider
      testrail_project: GraphQL Core module
      pagerduty_skip_notification: true
      provisioning_manifest: provisioning-manifest-build.yml
      should_use_build_artifacts: true
      artifact_prefix: gql
      static_analysis_auditci_level: critical
      module_branch: ${{ github.head_ref }}
      build_instance_type: self-hosted
      tests_standalone: true
