name: On Merge

on:
  push:
    tags-ignore:
      - '**'

jobs:
  merge:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-module-on-merge.yml@reusable-module-workflows
    secrets: inherit
